project:
  name: "Phoenix Multimodal LLM"
  root_directory: "/project/root"
  log_directory: "/logs"
  data_directory: "/data"
  model_directory: "/models"
  pretrained_directory: "/pretrained/models"

data:
  raw:
    text_path: "/data/raw/text"
    image_path: "/data/raw/images"
    audio_path: "/data/raw/audio"
  processed:
    text_path: "/data/processed/text"
    image_path: "/data/processed/images"
    audio_path: "/data/processed/audio"
  features_path: "/data/features"
  augmentation_scripts: "/data/scripts/augmentation.py"

model:
  architecture:
    text_model: "gpt_model"
    image_model: "vit_model"
    audio_model: "rnn_audio_model"
    multimodal_fusion: "fusion_model"
  pretrained: true
  pretrained_path: "/models/pretrained"
  
training:
  batch_size: 64
  learning_rate: 0.001
  epochs: 100
  optimizer: "adam"
  scheduler: "cosine_annealing"
  loss_function: "cross_entropy"

experiment:
  results_directory: "/experiments/results"
  config_directory: "/experiments/configs"
  log_metrics: true

hyperparameters:
  grid_search: true
  parameters:
    - learning_rate: [0.001, 0.0005, 0.0001]
    - batch_size: [32, 64, 128]

deployment:
  docker:
    dockerfile: "/deployment/docker/Dockerfile"
    compose_file: "/deployment/docker-compose.yml"
  cloud_platforms:
    aws: "/deployment/scripts/deploy_aws.py"
    gcp: "/deployment/scripts/deploy_gcp.py"
    azure: "/deployment/scripts/deploy_azure.py"

logging:
  enable: true
  log_level: "INFO"
  logger_script: "/logging/logger.py"
  logger_cpp_script: "/logging/logger_cpp.cpp"

monitoring:
  enable: true
  performance_metrics: true
  monitoring_script: "/monitoring/monitor.py"
  mlflow_integration: true
  mlflow_script: "/mlops/mlflow_integration.py"

testing:
  enable: true
  test_model_script: "/tests/test_models.py"
  test_data_pipeline_script: "/tests/test_data_pipeline.py"
  test_api_script: "/tests/test_api.py"
  cpp_tests: true
  test_cpp_model_script: "/tests/test_models_cpp.cpp"