name: Continuous Integration

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deployment/api/requirements.txt

      - name: Set up C++ build environment
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python Tests
        run: |
          python -m unittest discover -s tests -p "*.py"

      - name: Build and Test C++ Code
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ctest

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python linters
        run: |
          pip install flake8 black

      - name: Lint Python Code
        run: |
          flake8 .
          black --check .

      - name: Lint C++ Code
        run: |
          sudo apt-get install cppcheck
          cppcheck --enable=all --inconclusive --force --error-exitcode=1 .